### PR TITLE
Check for null while checking for rows in grid children

### PR DESCRIPTION
**Pull request by itsrifat**
The following fails because of no null check in  [this](https://github.com/GeekyAnts/react-native-easy-grid/blob/master/Components/Grid.js#L31) line.

```
const SomeComponent = () => (
  <Grid>
    <Col>Col1</Col>
    { someCondition && <Col>Col2</Col>} // this renders a falsy node here if condition not met
  <Grid>
)

```

### CODE REVIEW

**Comment by rigobcastro** [comment]
Great solution, thanks!

**Comment by itsrifat** [comment]
@rigobcastro, You can still use it in the following way though:

```
const SomeComponent = () => (
  <Grid>
    <Row>
      <Col>Col1</Col>
      { someCondition && <Col>Col2</Col>} // this should render ok
    </Row>
  <Grid>
)
```

**Comment by rigobcastro** [comment]
@itsrifat Error appears without your solution

**Comment by bang88** [comment]
Why not merge this PR. seems its a bug should be fixed .

**Pull request merged**
