### PR TITLE
Allow rows to have fixed height

### PR DESCRIPTION
**Pull request by ianfisk**
A fix for this [issue](https://github.com/GeekyAnts/react-native-easy-grid/issues/9)

### CODE REVIEW

**Comment by ianfisk** [comment]
A fix for this [issue](https://github.com/GeekyAnts/react-native-easy-grid/issues/9)

**Comment by sankhadeeproy007** [comment]
Nice! Thanks for the PR!

**Comment by sanketsahusoft** [comment]
@sankhadeeproy007 Do we need to document this? If so, let @SupriyaKalghatgi know about that same.

**Comment by ianfisk** [comment]
Anytime!

**Comment by sankhadeeproy007** [comment]
@sanketsahusoft There won't be any need for changes in the docs. It's already there.

**Pull request merged**
