### PR TITLE
Fixed import of ReactNativePropRegistry

### PR DESCRIPTION
**Pull request by lockeyo**
Fixes import of ReactNativePropRegistry

### CODE REVIEW

**Comment by sankhadeeproy007** [comment]
Hi @lockeyo , which version of react-native is this change for?

**Comment by lockeyo** [comment]
react-native-cli: 1.3.0
react-native: 0.37.0

**Comment by nitindhar7** [comment]
Any word on when this can be merged in?

**Comment by sankhadeeproy007** [comment]
This fix is for react-native version <0.38, so there's no point merging it now.

**Pull request closed without merging**
