### PR TITLE
Adding onpress

### PR DESCRIPTION
**Pull request by ddobby94**
I had some conflicts in the previous pull request, repaired them. Now it is compatible. Added the onPress property to the Row, Col, Grid components.

### CODE REVIEW

**Comment by adambene** [comment]
hey guys, what about accepting this nice PR? :)

**Comment by adambene** [comment]
is this repo maintained?

**Comment by adambene** [comment]
Could you merge this PR or give write permissions?

**Comment by sankhadeeproy007** [comment]
@ddobby94 @adambene Do we really need to nest it inside a `TouchableOpacity`? I think `onPress` works with `View` as well. What do you guys say?

**Comment by ddobby94** [comment]
@sankhadeeproy007 Unfortunately the `View` component does not support the `onPress` property. (using RN 0.35)

**Comment by adambene** [comment]
@sankhadeeproy007 could you release this feature? thx

**Comment by sankhadeeproy007** [comment]
Done!

**Pull request merged**
