### PR TITLE
Fixes failed to find module in react-native 0.36.0

### PR DESCRIPTION
**Pull request by jimmyhmiller**
This was suggest [here](https://github.com/GeekyAnts/NativeBase/issues/328#issuecomment-263552829) and seems to solve the problem.

### CODE REVIEW

**Comment by alanlanglois** [comment]
Would be awesome to merge :)

**Comment by JuhQ** [comment]
+1 for merge!

**Comment by JuhQ** [comment]
I tried emailing GeekyAnts people about this pr and the emails bounced. Is this project abandonware?

**Comment by sanketsahusoft** [comment]
@JuhQ We are fixing this. Give us time until tomorrow. This isn't abandoned. Long live EasyGrid!

**Comment by JuhQ** [comment]
You have 24 hours

**Comment by sanketsahusoft** [comment]
@JuhQ Now you're scaring me dude! 😨

**Comment by SupriyaKalghatgi** [comment]
@jimmyhmiller Thank you

**Comment by JuhQ** [comment]
Nice! Let's get this change to npm and to the community! :)

**Comment by sankhadeeproy007** [comment]
This PR actually broke the current version. RN changed the propRegistry path with RN 38 onwards. So that previous version (which we had) was actually correct. Let's revert back @himanshu-satija @SupriyaKalghatgi

**Comment by sanketsahusoft** [comment]
@SupriyaKalghatgi Please do add JEST snapshot test here as well along with Travis CI. So that if PR is failing or passing.

**Comment by SupriyaKalghatgi** [comment]
Fixed with 0.1.6

**Pull request merged**
